# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Esteban Ramos
tagline:             stuff
description:         This is simply a place to outline my work and write about things
url:                 https://EIRNf.github.io
baseurl:             ''
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

# About/contact
author:
  name:              Esteban Ramos
  url:               https://EIRNf.github.io
  email:             estebanramo@gmail.com

